import React, { useState, useMemo } from 'react';
import { AUDITOR_GENERAL_FINDINGS } from '../data/auditorGeneralFindings';
import { AuditorGeneralFinding, AuditFindingCategory, Candidate } from '../types';
import { 
  FileText, 
  AlertTriangle, 
  ShieldAlert, 
  Search, 
  Filter, 
  Building2, 
  DollarSign, 
  ExternalLink, 
  ChevronRight, 
  Scale, 
  CheckCircle2, 
  Plane, 
  Car, 
  GraduationCap, 
  Layers, 
  Users, 
  Briefcase, 
  Landmark, 
  Download, 
  Share2, 
  Sparkles,
  Video
} from 'lucide-react';
import { downloadFile } from '../utils/download';

interface AuditorGeneralFindingsHubProps {
  candidates?: Candidate[];
  onSelectCandidate?: (candidate: Candidate) => void;
  onOpenAddEvidence?: (candidate?: Candidate) => void;
}

export const AuditorGeneralFindingsHub: React.FC<AuditorGeneralFindingsHubProps> = ({
  candidates = [],
  onSelectCandidate,
  onOpenAddEvidence
}) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('ALL');
  const [selectedFinding, setSelectedFinding] = useState<AuditorGeneralFinding | null>(null);

  const formatKsh = (amount: number) => {
    if (amount >= 1000000000) return `KSh ${(amount / 1000000000).toFixed(2)} Billion`;
    if (amount >= 1000000) return `KSh ${(amount / 1000000).toFixed(2)} Million`;
    return `KSh ${amount.toLocaleString()}`;
  };

  const getCategoryIcon = (category: AuditFindingCategory) => {
    switch (category) {
      case 'ifmis_voided':
        return <Layers className="w-5 h-5 text-red-500" />;
      case 'unconfirmed_grants':
        return <DollarSign className="w-5 h-5 text-amber-500" />;
      case 'pending_bills':
        return <Building2 className="w-5 h-5 text-orange-500" />;
      case 'ghost_workers':
        return <Users className="w-5 h-5 text-rose-500" />;
      case 'domestic_travel':
        return <Plane className="w-5 h-5 text-red-600" />;
      case 'transport_fuel':
        return <Car className="w-5 h-5 text-amber-600" />;
      case 'training_workshops':
        return <GraduationCap className="w-5 h-5 text-yellow-500" />;
      case 'legal_fees':
        return <Scale className="w-5 h-5 text-purple-500" />;
      case 'land_acquisition':
        return <Landmark className="w-5 h-5 text-emerald-500" />;
      case 'crf_cut_off':
        return <AlertTriangle className="w-5 h-5 text-red-600" />;
      default:
        return <FileText className="w-5 h-5 text-neutral-400" />;
    }
  };

  const filteredFindings = useMemo(() => {
    return AUDITOR_GENERAL_FINDINGS.filter((finding) => {
      const matchesSearch = 
        finding.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        finding.categoryLabel.toLowerCase().includes(searchQuery.toLowerCase()) ||
        finding.entityOrCounty.toLowerCase().includes(searchQuery.toLowerCase()) ||
        finding.summary.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (finding.relatedLeaders && finding.relatedLeaders.some(l => l.toLowerCase().includes(searchQuery.toLowerCase())));

      const matchesCategory = selectedCategory === 'ALL' || finding.category === selectedCategory;

      return matchesSearch && matchesCategory;
    });
  }, [searchQuery, selectedCategory]);

  const totalQuestionedFunds = useMemo(() => {
    return AUDITOR_GENERAL_FINDINGS.reduce((sum, f) => sum + f.amountQuestionedKsh, 0);
  }, []);

  const handleDownloadDossier = (finding: AuditorGeneralFinding) => {
    const text = `=====================================================
OFFICE OF THE AUDITOR-GENERAL (OAG KENYA) FORENSIC DOSSIER
Source: Auditor-General Nancy Gathungu Reports via @civicsnsins ('THE ACCOUNTANT')
=====================================================
CATEGORY: ${finding.categoryLabel}
TITLE: ${finding.title}
AMOUNT QUESTIONED: ${formatKsh(finding.amountQuestionedKsh)} (KES ${finding.amountQuestionedKsh.toLocaleString()})
AFFECTED ENTITY: ${finding.entityOrCounty}
FINANCIAL YEAR: ${finding.financialYear}
OFFICIAL OAG DOCKET REF: ${finding.oagReportRef}
CIVIC CREATOR VERIFICATION: ${finding.tiktokCreatorRef || '@civicsnsins'}
STATUS: ${finding.status}

SUMMARY OF AUDIT QUERY:
${finding.summary}

SPECIFIC ANOMALIES & AUDIT BREACHES:
${finding.detailedAnomalies.map((a, i) => `${i + 1}. ${a}`).join('\n')}

RELATED POLITICAL ACTORS / EXECUTIVES:
${finding.relatedLeaders ? finding.relatedLeaders.join(', ') : 'County & National Accounting Officers'}

LEGAL FRAMEWORK CITED:
• Public Finance Management (PFM) Act 2012
• Public Procurement and Asset Disposal Act (PPADA) 2015
• Article 229 & Article 207 of the Constitution of Kenya 2010

Official Source Link: ${finding.sourceUrl || 'https://www.oagkenya.go.ke'}
=====================================================
Generated by Chaguo 2027 Civic Accountability Platform`;
    downloadFile(`OAG_AUDIT_${finding.id}.txt`, text, 'text/plain');
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="bg-gradient-to-br from-neutral-900 via-neutral-950 to-red-950 text-white border-2 border-red-600/40 rounded-2xl p-5 sm:p-6 shadow-xl relative overflow-hidden">
        <div className="relative z-10 space-y-3">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <span className="px-2.5 py-1 bg-red-600 text-white text-[10px] font-black uppercase tracking-wider rounded-md flex items-center gap-1">
                <ShieldAlert className="w-3.5 h-3.5" />
                Nancy Gathungu OAG Reports
              </span>
              <span className="px-2.5 py-1 bg-pink-600/20 text-pink-300 border border-pink-500/40 text-[10px] font-black uppercase tracking-wider rounded-md flex items-center gap-1">
                <Video className="w-3.5 h-3.5" />
                @civicsnsins TikTok Breakdown
              </span>
            </div>

            <div className="text-right">
              <span className="text-[10px] font-black uppercase text-neutral-400 block">Total Flagged Irregularities</span>
              <span className="text-lg sm:text-xl font-black text-red-400 font-mono">
                {formatKsh(totalQuestionedFunds)}
              </span>
            </div>
          </div>

          <h2 className="text-xl sm:text-2xl font-black uppercase tracking-tight">
            Key Audit Findings from the Auditor-General's Report
          </h2>
          <p className="text-xs sm:text-sm text-neutral-300 max-w-3xl leading-relaxed">
            Forensic breakdown of questioned public expenditures, voided IFMIS transactions, phantom ghost workers, and unconfirmed inter-agency grants as documented by the Office of the Auditor-General and exposed by civic content creators.
          </p>
        </div>
      </div>

      {/* Filter & Search Bar */}
      <div className="p-4 bg-white dark:bg-neutral-900 border-2 border-neutral-200 dark:border-neutral-800 rounded-2xl space-y-3 shadow-md">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div className="relative">
            <Search className="w-4 h-4 absolute left-3 top-3 text-neutral-400" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search finding, category, county (e.g. IFMIS, Nakuru, Domestic Travel)..."
              className="w-full pl-9 pr-3 py-2 bg-neutral-100 dark:bg-neutral-800 border border-neutral-300 dark:border-neutral-700 rounded-xl text-xs font-bold text-neutral-900 dark:text-neutral-100 placeholder-neutral-500"
            />
          </div>

          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="px-3 py-2 bg-neutral-100 dark:bg-neutral-800 border border-neutral-300 dark:border-neutral-700 rounded-xl text-xs font-bold text-neutral-800 dark:text-neutral-200"
          >
            <option value="ALL">All Audit Finding Categories ({AUDITOR_GENERAL_FINDINGS.length})</option>
            <option value="ifmis_voided">Voided IFMIS Transactions (KSh 560.6M)</option>
            <option value="crf_cut_off">CRF Revenue Cut-Off Discrepancies (KSh 7.09B)</option>
            <option value="ghost_workers">Employee Compensation & Ghost Workers (KSh 2.87B)</option>
            <option value="pending_bills">Questionable Pending Bills (KSh 1.46B)</option>
            <option value="unconfirmed_grants">Unconfirmed Grants & Transfers (KSh 713.7M)</option>
            <option value="transport_fuel">Transport & Fleet Questioned (KSh 70.7M)</option>
            <option value="domestic_travel">Domestic Travel Questioned (KSh 51.7M)</option>
            <option value="legal_fees">Single-Sourced Legal Fees (KSh 34.6M)</option>
            <option value="land_acquisition">Land Acquisition Without Title (KSh 32.9M)</option>
            <option value="training_workshops">Training & Luxury Workshops (KSh 14.5M)</option>
          </select>
        </div>
      </div>

      {/* Grid of Audit Finding Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {filteredFindings.map((finding) => (
          <div
            key={finding.id}
            onClick={() => setSelectedFinding(finding)}
            className="p-5 bg-white dark:bg-neutral-900 border-2 border-neutral-200 dark:border-neutral-800 hover:border-red-600 dark:hover:border-red-500 rounded-2xl transition-all shadow-md hover:shadow-xl cursor-pointer group flex flex-col justify-between"
          >
            <div className="space-y-3">
              {/* Header */}
              <div className="flex items-start justify-between gap-2">
                <div className="flex items-center gap-2">
                  <div className="p-2 bg-neutral-100 dark:bg-neutral-800 border border-neutral-200 dark:border-neutral-700 rounded-xl group-hover:scale-110 transition-transform">
                    {getCategoryIcon(finding.category)}
                  </div>
                  <div>
                    <span className="text-[10px] font-black uppercase text-red-600 dark:text-red-400 tracking-wider block">
                      {finding.categoryLabel}
                    </span>
                    <span className="text-[10px] font-bold text-neutral-500">
                      {finding.entityOrCounty} • {finding.financialYear}
                    </span>
                  </div>
                </div>

                <span className="px-2 py-0.5 bg-red-600 text-white text-[9px] font-black uppercase rounded-md shrink-0">
                  {finding.status.replace(/_/g, ' ')}
                </span>
              </div>

              {/* Amount Questioned Highlight */}
              <div className="p-3 bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-900/50 rounded-xl flex items-center justify-between">
                <span className="text-[10px] font-black uppercase text-red-700 dark:text-red-300">
                  Questioned Amount:
                </span>
                <span className="text-base sm:text-lg font-black font-mono text-red-600 dark:text-red-400">
                  {formatKsh(finding.amountQuestionedKsh)}
                </span>
              </div>

              {/* Title & Summary */}
              <h3 className="text-sm font-black uppercase tracking-tight text-neutral-900 dark:text-white group-hover:text-red-600 dark:group-hover:text-red-400 transition-colors">
                {finding.title}
              </h3>

              <p className="text-xs text-neutral-600 dark:text-neutral-300 line-clamp-3 leading-relaxed">
                {finding.summary}
              </p>
            </div>

            {/* Footer Meta */}
            <div className="pt-4 mt-3 border-t border-neutral-100 dark:border-neutral-800 flex items-center justify-between text-[10px] font-bold text-neutral-500">
              <span className="flex items-center gap-1 text-pink-600 dark:text-pink-400">
                <Video className="w-3 h-3" />
                {finding.tiktokCreatorRef || '@civicsnsins'}
              </span>
              <span className="text-red-600 dark:text-red-400 group-hover:underline flex items-center gap-0.5">
                Inspect Dossier <ChevronRight className="w-3 h-3" />
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Modal / Detailed Drawer for Selected Finding */}
      {selectedFinding && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-xs flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
          <div className="bg-white dark:bg-neutral-900 border-2 border-neutral-800 dark:border-neutral-700 rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto shadow-2xl p-5 sm:p-6 space-y-5">
            {/* Modal Header */}
            <div className="flex items-start justify-between gap-3 border-b border-neutral-200 dark:border-neutral-800 pb-4">
              <div className="flex items-center gap-2.5">
                <div className="p-2.5 bg-red-600/10 border border-red-500/20 text-red-600 rounded-xl">
                  {getCategoryIcon(selectedFinding.category)}
                </div>
                <div>
                  <span className="text-[10px] font-black uppercase text-red-600 dark:text-red-400 tracking-wider block">
                    {selectedFinding.categoryLabel}
                  </span>
                  <h2 className="text-lg font-black uppercase tracking-tight text-neutral-900 dark:text-white">
                    {selectedFinding.title}
                  </h2>
                </div>
              </div>

              <button
                onClick={() => setSelectedFinding(null)}
                className="p-1.5 bg-neutral-100 dark:bg-neutral-800 hover:bg-neutral-200 rounded-lg text-neutral-500 font-black text-sm"
              >
                ✕
              </button>
            </div>

            {/* Key Stats Row */}
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5">
              <div className="p-3 bg-neutral-100 dark:bg-neutral-800 rounded-xl">
                <span className="text-[9px] font-black uppercase text-neutral-500 block">Questioned Amount</span>
                <span className="text-sm font-black font-mono text-red-600 dark:text-red-400 block">
                  {formatKsh(selectedFinding.amountQuestionedKsh)}
                </span>
              </div>
              <div className="p-3 bg-neutral-100 dark:bg-neutral-800 rounded-xl">
                <span className="text-[9px] font-black uppercase text-neutral-500 block">Target Entity</span>
                <span className="text-xs font-black text-neutral-800 dark:text-neutral-200 block truncate">
                  {selectedFinding.entityOrCounty}
                </span>
              </div>
              <div className="p-3 bg-neutral-100 dark:bg-neutral-800 rounded-xl col-span-2 sm:col-span-1">
                <span className="text-[9px] font-black uppercase text-neutral-500 block">OAG Docket Ref</span>
                <span className="text-[10px] font-mono font-bold text-neutral-700 dark:text-neutral-300 block truncate">
                  {selectedFinding.oagReportRef}
                </span>
              </div>
            </div>

            {/* Audit Query Summary */}
            <div className="space-y-2">
              <h4 className="text-xs font-black uppercase tracking-wider text-neutral-800 dark:text-neutral-200">
                Auditor-General Formal Query Summary:
              </h4>
              <p className="text-xs text-neutral-700 dark:text-neutral-300 leading-relaxed bg-neutral-50 dark:bg-neutral-950 p-3.5 rounded-xl border border-neutral-200 dark:border-neutral-800 font-medium">
                {selectedFinding.summary}
              </p>
            </div>

            {/* Detailed Anomalies */}
            <div className="space-y-2">
              <h4 className="text-xs font-black uppercase tracking-wider text-neutral-800 dark:text-neutral-200">
                Specific Documented Anomalies & Violations:
              </h4>
              <ul className="space-y-2">
                {selectedFinding.detailedAnomalies.map((item, idx) => (
                  <li key={idx} className="text-xs text-neutral-700 dark:text-neutral-300 flex items-start gap-2 p-2.5 bg-neutral-50 dark:bg-neutral-800/40 rounded-lg border border-neutral-200 dark:border-neutral-700/60">
                    <span className="w-5 h-5 bg-red-600 text-white rounded-full text-[10px] font-black flex items-center justify-center shrink-0 mt-0.5">
                      {idx + 1}
                    </span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Related Leaders */}
            {selectedFinding.relatedLeaders && selectedFinding.relatedLeaders.length > 0 && (
              <div className="space-y-2">
                <h4 className="text-xs font-black uppercase tracking-wider text-neutral-800 dark:text-neutral-200">
                  Related Political Actors & Accounting Officers:
                </h4>
                <div className="flex flex-wrap gap-2">
                  {selectedFinding.relatedLeaders.map((leader, i) => {
                    const candObj = candidates.find(c => c.name.toLowerCase().includes(leader.toLowerCase()));
                    return (
                      <button
                        key={i}
                        onClick={() => {
                          if (candObj && onSelectCandidate) {
                            setSelectedFinding(null);
                            onSelectCandidate(candObj);
                          }
                        }}
                        className="px-3 py-1.5 bg-neutral-100 dark:bg-neutral-800 hover:bg-red-600 hover:text-white border border-neutral-300 dark:border-neutral-700 rounded-xl text-xs font-black uppercase transition-colors flex items-center gap-1"
                      >
                        <span>{leader}</span>
                        {candObj && <span className="text-[10px] opacity-75">({candObj.position})</span>}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Action Buttons */}
            <div className="flex flex-wrap items-center justify-between gap-3 pt-3 border-t border-neutral-200 dark:border-neutral-800">
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleDownloadDossier(selectedFinding)}
                  className="px-3.5 py-2 bg-neutral-900 hover:bg-neutral-800 text-white dark:bg-neutral-100 dark:text-neutral-900 text-xs font-black uppercase rounded-xl transition-colors flex items-center gap-1.5 shadow-sm"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download OAG Dossier</span>
                </button>

                {onOpenAddEvidence && (
                  <button
                    onClick={() => {
                      const matched = candidates.find(c => selectedFinding.relatedLeaders?.some(l => c.name.toLowerCase().includes(l.toLowerCase())));
                      setSelectedFinding(null);
                      onOpenAddEvidence(matched);
                    }}
                    className="px-3.5 py-2 bg-red-600 hover:bg-red-700 text-white text-xs font-black uppercase rounded-xl transition-colors flex items-center gap-1.5 shadow-sm"
                  >
                    <span>+ Attach New Evidence</span>
                  </button>
                )}
              </div>

              <a
                href={selectedFinding.sourceUrl || 'https://www.oagkenya.go.ke'}
                target="_blank"
                rel="noreferrer"
                className="text-xs font-black uppercase text-neutral-600 dark:text-neutral-400 hover:text-red-600 flex items-center gap-1"
              >
                <span>Official OAG Portal</span>
                <ExternalLink className="w-3.5 h-3.5" />
              </a>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
